### ISSUE TITLE
Link to "Modern Machine Learning in R" vignette does not work

### ISSUE THREAD

**Issue by aolinw** [tlbbd-spring2018/lab_06#1]
Hi Nima, 
Could you help check? Thank you very much.
Aolin

**Comment by nhejazi** [comment]
Hi Aolin ---

Thanks for reporting this. We were in the process of moving the `sl3` package to a new location and now that this migration is complete, I've corrected the links in the Jupyter notebook. Please let me know if you have any further problems accessing the vignette. I'll close this issue for now but feel free to re-open.
